/**
 * Copyright (c) 2017 Drishti-Soft Solutions Pvt. Ltd.
 *
 * @author: anupam
 * Date:  Jun 26, 2017
 */
package com.pickup.order.assignment.handler.impl.service;

import java.util.ArrayList;
import java.util.List;

import com.pickup.order.assignment.handler.api.entities.IRestaurantBean;
import com.pickup.order.assignment.handler.api.service.IRestaurantManagerService;
import com.pickup.order.assignment.handler.bean.RestaurantBean;

/**
 *
 */
public class RestaurantManagerService implements IRestaurantManagerService {

    private List<RestaurantBean> restaurantsList = null;
    private static RestaurantManagerService instance = null;
    private static int autoGeneratedRestaurantId = 1; //generates and assigns unique ids to each new restaurant

    public static synchronized RestaurantManagerService getInstance() {
        if (instance == null) {
            instance = new RestaurantManagerService();
        }

        return instance;
    }

    private RestaurantManagerService() {
        restaurantsList = new ArrayList<RestaurantBean>();
    }

    @Override
    public IRestaurantBean getRestaurantById(String restaurantId) {
        synchronized (restaurantsList) {
            for (RestaurantBean restaurantBean : restaurantsList) {
                if (restaurantBean.getRestaurantId() != null && restaurantBean.getRestaurantId().equals(restaurantId)) {
                    return new RestaurantBean(restaurantBean);
                }
            }
        }
        return null;
    }

    @Override
    public List<String> addRestaurantList(List<IRestaurantBean> restaurantListToBeAdded) {
        List<RestaurantBean> clonedRestaurantListToBeAdded = new ArrayList<RestaurantBean>();
        List<String> restaurantIdsList = new ArrayList<String>();
        for (IRestaurantBean restaurantBeanToBeAdded : restaurantListToBeAdded) {
            RestaurantBean clonedRestaurantBeanToBeAdded = new RestaurantBean(
                    String.valueOf(autoGeneratedRestaurantId++), restaurantBeanToBeAdded.getRestaurantName(),
                    restaurantBeanToBeAdded.getRestaurantLocationsLatitude(),
                    restaurantBeanToBeAdded.getRestaurantLocationsLongitude());
            clonedRestaurantListToBeAdded.add(clonedRestaurantBeanToBeAdded);
            restaurantIdsList.add(clonedRestaurantBeanToBeAdded.getRestaurantId());
        }
        synchronized (restaurantsList) {
            restaurantsList.addAll(clonedRestaurantListToBeAdded);
        }
        return restaurantIdsList;
    }
}
